### ISSUE TITLE
Why does the Organizer event creation page include a notifications toggle?

### ISSUE THREAD

**Issue by ahmedsiad** [CMPUT301F24dragon/lucky-dragons#25]
The event creation fragment has an option to toggle notifications on or off for an event. I'm not sure why we have this, I don't see any user story for organizers to turn off notifications for an event.

There is a user story for an entrant to turn off notifications:
> US 01.04.03 As an entrant I want to opt out of receiving notifications from organizers and admin

But this is just for the entrant to turn off ALL notifications. Should we remove this toggle on events?

**Comment by matthew-fischer** [comment]
Isn't there a task for organizer to toggle notification for an
